#!/bin/bash

if [ $# -ne 1 ] ; then
    echo "Usage $0 <version string>"
    exit 1
fi

input_version=$1

if ! [[ $input_version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ; then
    echo "Input must match: <number>.<number>.<number>"
    exit 1
fi

awk -F. '/[0-9]+\./{$NF+=1;print}' OFS=. <<< ${input_version}
